security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: api_token
    firewalls:
        main:
            pattern: ^/
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator

    access_control:
        - { path: ^/, roles: 'ROLE_USER' }